// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmsmfmhbzkaznfirfsng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtc21mbWhiemthem5maXJmc25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTg5ODcsImV4cCI6MjA3MjU3NDk4N30.s-9S6xUXSVO_9LtVzncFAKMkuNOQi2IrCtUP-SUkAmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});